COQDOCJS_DIR ?= coqdocjs
EXTRA_DIR = $(COQDOCJS_DIR)/extra
COQDOCFLAGS ?= \
  --toc --toc-depth 2 --html --interpolate \
  --index indexpage --no-lib-name --parse-comments \
  --with-header $(EXTRA_DIR)/header.html --with-footer $(EXTRA_DIR)/footer.html \
  $(COQDOCEXTRAFLAGS)
export COQDOCFLAGS
COQMAKEFILE ?= Makefile.coq
COQDOCJS_CP ?= false
COQDOCJS_CUSTOM ?= $(EXTRA_DIR)/custom

html: $(COQMAKEFILE)
	@$(MAKE) -f $^ $@
	ln -sf toc.html $@/index.html
ifeq ($(COQDOCJS_CP),true)
	cp -R $(EXTRA_DIR)/resources $@
	cp -R $(COQDOCJS_CUSTOM) $@/custom
else
	ln -sf ../$(EXTRA_DIR)/resources $@
	ln -sf ../$(COQDOCJS_CUSTOM) $@/custom
endif

.PHONY: html
